//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assistant_specialist.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class PositiveResponseSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static PositiveResponseSettings defaultInstance = ((PositiveResponseSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new PositiveResponseSettings())));
        
        public static PositiveResponseSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FullPostalAddress {
            get {
                return ((bool)(this["FullPostalAddress"]));
            }
            set {
                this["FullPostalAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeclensionFullName {
            get {
                return ((bool)(this["DeclensionFullName"]));
            }
            set {
                this["DeclensionFullName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string PositionSignDocuments {
            get {
                return ((string)(this["PositionSignDocuments"]));
            }
            set {
                this["PositionSignDocuments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NameSignDocuments {
            get {
                return ((string)(this["NameSignDocuments"]));
            }
            set {
                this["NameSignDocuments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowSpecialist {
            get {
                return ((bool)(this["ShowSpecialist"]));
            }
            set {
                this["ShowSpecialist"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string NameSpecialist {
            get {
                return ((string)(this["NameSpecialist"]));
            }
            set {
                this["NameSpecialist"] = value;
            }
        }
    }
}
