//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assistant_specialist.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assistant_specialist.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фактический адрес проживания.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный адрес.
        /// </summary>
        public static string AddressNotValid {
            get {
                return ResourceManager.GetString("AddressNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма долга.
        /// </summary>
        public static string AmountDebt {
            get {
                return ResourceManager.GetString("AmountDebt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректная сумма долга.
        /// </summary>
        public static string AmountDebtNotValid {
            get {
                return ResourceManager.GetString("AmountDebtNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма перерасчета.
        /// </summary>
        public static string AmountRecalculation {
            get {
                return ResourceManager.GetString("AmountRecalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректная сумма перерасчета.
        /// </summary>
        public static string AmountRecalculationNotValid {
            get {
                return ResourceManager.GetString("AmountRecalculationNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить введенные данные.
        /// </summary>
        public static string ApplyInputData {
            get {
                return ResourceManager.GetString("ApplyInputData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДАННЫЕ ПО ДОГОВОРУ.
        /// </summary>
        public static string ContractData {
            get {
                return ResourceManager.GetString("ContractData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата договора.
        /// </summary>
        public static string ContractDate {
            get {
                return ResourceManager.GetString("ContractDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата договора не определена.
        /// </summary>
        public static string ContractDateNotValid {
            get {
                return ResourceManager.GetString("ContractDateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Номер договора.
        /// </summary>
        public static string ContractNumber {
            get {
                return ResourceManager.GetString("ContractNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный номер договора.
        /// </summary>
        public static string ContractNumberNotValid {
            get {
                return ResourceManager.GetString("ContractNumberNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата расторжения.
        /// </summary>
        public static string ContractTerminationDate {
            get {
                return ResourceManager.GetString("ContractTerminationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата расторжения меньше даты договора.
        /// </summary>
        public static string ContractTerminationDateNotValid {
            get {
                return ResourceManager.GetString("ContractTerminationDateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Склонение имени.
        /// </summary>
        public static string Declension {
            get {
                return ResourceManager.GetString("Declension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата окончания скидки.
        /// </summary>
        public static string EndDateDiscounts {
            get {
                return ResourceManager.GetString("EndDateDiscounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия Имя Отчество.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректное Ф.И.О. абонента.
        /// </summary>
        public static string FullNameNotValid {
            get {
                return ResourceManager.GetString("FullNameNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пол:.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ИСХОДЯЩИЕ ДАННЫЕ.
        /// </summary>
        public static string OutgoingData {
            get {
                return ResourceManager.GetString("OutgoingData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата ответа.
        /// </summary>
        public static string OutgoingDate {
            get {
                return ResourceManager.GetString("OutgoingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата ответа меньше даты договора.
        /// </summary>
        public static string OutgoingDateNotValid {
            get {
                return ResourceManager.GetString("OutgoingDateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исходящий номер.
        /// </summary>
        public static string OutgoingNumber {
            get {
                return ResourceManager.GetString("OutgoingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный исходящий номер.
        /// </summary>
        public static string OutgoingNumberNotValid {
            get {
                return ResourceManager.GetString("OutgoingNumberNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Положительный ответ тест.
        /// </summary>
        public static string PositiveResponse {
            get {
                return ResourceManager.GetString("PositiveResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Печать документа.
        /// </summary>
        public static string PrintingDocument {
            get {
                return ResourceManager.GetString("PrintingDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата начала скидки.
        /// </summary>
        public static string StartDateDiscount {
            get {
                return ResourceManager.GetString("StartDateDiscount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Даты скидок меньше даты договора.
        /// </summary>
        public static string StartEndDateDiscountNotValid1 {
            get {
                return ResourceManager.GetString("StartEndDateDiscountNotValid1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Некорректный диапазон дат.
        /// </summary>
        public static string StartEndDateDiscountNotValid2 {
            get {
                return ResourceManager.GetString("StartEndDateDiscountNotValid2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявление на перерасчет.
        /// </summary>
        public static string StatementRecalculation {
            get {
                return ResourceManager.GetString("StatementRecalculation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата заявления на перерасчет.
        /// </summary>
        public static string StatementRecalculationDate {
            get {
                return ResourceManager.GetString("StatementRecalculationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата заявл. на перер. меньше даты дог..
        /// </summary>
        public static string StatementRecalculationDateNotValid {
            get {
                return ResourceManager.GetString("StatementRecalculationDateNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявление на расторжение.
        /// </summary>
        public static string StatementTermination {
            get {
                return ResourceManager.GetString("StatementTermination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ДАННЫЕ АБОНЕНТА.
        /// </summary>
        public static string SubscriberData {
            get {
                return ResourceManager.GetString("SubscriberData", resourceCulture);
            }
        }
    }
}
